### ISSUE TITLE
How do I get the resolved URL for a component link?

### ISSUE THREAD

**Issue by chadyu** [dd4t/dd4t-2-java#41] opened 2016-02-18 22:31 UTC
org.dd4t.core.processors.impl.LinkingProcessor.resolveComponent(Component component) method does not set the resolved url for the component anywhere.
    protected void resolveComponent (Component component) throws TransformerException {
        try {
            if (component != null) {
                resolveMap(component.getContent());
                resolveMap(component.getMetadata());
                linkResolver.resolve(component);
            }
        } catch (ItemNotFoundException | SerializationException e) {
            throw new TransformerException(e);
        }
    }

**Comment by RaimondKempees** [comment] 2016-02-19 10:22
You're right. That code actually doesn't make sense and something will be done about it. 

In the meatime, to get a resolved URL, it's best to use:

LinkResolver linkResolver = (LinkResolver)JspBeanContext.getBean("linkResolver");
String resolved = linkResolver.resolve(component);

**Comment by RaimondKempees** [comment] 2016-05-05 15:37
The bug is now fixed. Leaving this open as enhancement ticket:

- There's need to put a resolved link on a ViewModel
- Obtaining the linkresolver can be done more elegant.

**Comment by RaimondKempees** [comment] 2016-05-05 15:38
Actually closing this. Duplicate of issue #37

**Closed by RaimondKempees** 2016-05-05 15:38 UTC
Labels: enhancement
